apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tmf-product-catalog-management-api
  description: API for Product Catalog Management
  tags:
    - tmf620
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  type: openapi
  lifecycle: experimental
  owner: team-tmf-product-catalog
  system: tmf-apis-system
  definition:
    $text: https://product-catalog-management-api-java-prod-w05-s004.cnr.emea.end2end.link/v3/api-docs.yaml