apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: product-catalog-management-api-java
  namespace: workshops-w04-s006
  labels:
    app.kubernetes.io/part-of: tmf-product-catalog-management-api-service
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    vodafone.com/check-api-conformance: "true"
spec:
  source:
    git:
      url: https://github.com/tsalm-pivotal/tm-forum-poc-ws-repo.git
      ref:
        branch: workshops-w04-s006-63d8894d-f9f4-4fa1-bfc3-73060baeae43
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: mongodb-binding-compatible