apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: product-catalog-management-api-java
  namespace: prod-w05-s003
  labels:
    app.kubernetes.io/part-of: tmf-product-catalog-management-api-service
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    vodafone.com/check-api-conformance: "true"
spec:
  source:
    git:
      url: https://github.com/tsalm-pivotal/tm-forum-poc-ws-repo.git
      ref:
        branch: prod-w05-s003-ec40d5c5-b374-40bb-afa8-3de52e23d136
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: mongodb-binding-compatible