apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: product-catalog-management-api-java
  namespace: workshops-w02-s002
  labels:
    app.kubernetes.io/part-of: tmf-product-catalog-management-api-service
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    vodafone.com/check-api-conformance: "true"
spec:
  source:
    git:
      url: $APP_GIT_REPO_HTTP_URL
      ref:
        branch: main
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: mongodb-binding-compatible